site:
  # Заголовок сайта, используется в хлебных крошках и ещё в некоторых местах меню
  title: Test
  # Ссылка на стартовую страницу, которая открывается по умолчанию при заходе на сайт с докой (на неё должна вести ссылка из всех источников)
  start_page: helpcenter:ROOT:index.adoc
urls:
  # Что отображается в урле, без этого параметра там будет номер версии из файла antora.yml
    latest_version_segment: stable
git:
  ensure_git_suffix: false
  fetch_concurrency: 10
runtime:
  fetch: true
  # Пишем лог в файл (при локальной сборке можно будет смотреть)
  log:
    #level: fatal
    format: pretty
    destination:
      file: ./docs_stats_reports/antora-en.log
content:
  sources:
  # Ссылка на AsciiDoc исходники
  - url: ./
    branches:
      - HEAD
    #  - release.0.10.1010
    worktrees: true
  # Ссылка, где лежат модули и файл antora.yml
    start_path: documentation-en
asciidoc:
# Установка расширения с поддержкой математических формул
  extensions:
   - '@djencks/asciidoctor-mathjax'
  attributes:
    language: en@
    404-page-title: Ошибка 404
    page-component-order: '!home, !ROOT, *, asciidoclet, reveal.js-converter, pdf-converter, epub3-converter, diagram-extension, about'
    extensions: '@djencks/asciidoctor-mathjax'
    experimental: ''
    idprefix: ''
    idseparator: '-'
    page-pagination: ''
    attribute-missing: warn@
# Ссылка на архив со стилями для сайта
ui:
  bundle:
    url: documentation-en/ui/ui-bundle.zip
# Ссылка на папку, в которой будет создана папка с собранным сайтом
output:
  dir: ./doc_pages/en
